### ISSUE TITLE
Type safety with Materials is needed

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#236] opened 2024-06-26 16:17 UTC

**Comment by zepumph** [comment] 2024-06-26 16:26
Related to https://github.com/phetsims/density-buoyancy-common/issues/163

**Comment by zepumph** [comment] 2024-07-03 22:52
Duplicate of https://github.com/phetsims/density-buoyancy-common/issues/176. Closing

**Closed as completed by zepumph** 2024-07-03 22:52 UTC
Labels: dev:code-review
