### ISSUE TITLE
iPad Graphical issues

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density-buoyancy-common#230] opened 2024-06-18 17:36 UTC
For https://github.com/phetsims/qa/issues/1095
On iPad, when objects were dragged/moved over the sky, often a graphical artifact of white boxes appeared. It seemed to occur most often when a second block was added, but not exclusively. I also had one instance where many objects seemed darker than they should. Reloading fixed that part of the issue, and I'm not sure how to reproduce it.
![IMG_0037](https://github.com/phetsims/density-buoyancy-common/assets/41024075/fbc18f83-3be5-460b-a011-d2dbba36997e)

**Comment by samreid** [comment] 2024-08-06 13:18
Also crashed on iphone in #315

**Comment by samreid** [comment] 2024-08-13 16:07
On hold on the off chance that https://github.com/phetsims/density-buoyancy-common/issues/316 solves it.

**Comment by samreid** [comment] 2024-08-20 02:54
I tested this quite a bit on a built version of buoyancy and couldn't reproduce the problem. @DianaTavares @arouinfar or @zepumph can you reproduce the problem?

**Comment by arouinfar** [comment] 2024-08-20 15:27
@samreid I cannot reproduce this on my iPad Pro or Mac. Graphical artifacts in mobile Safari aren't a new problem, see https://github.com/phetsims/scenery/issues/1503. We often have no choice but to live with them.

In FEL, we ran into an issue that initially appeared to be the typical graphical artifacts, but it also happened on Mac. The solution was to add a transparent rectangle behind the coil when running on Safari.
https://github.com/phetsims/faradays-electromagnetic-lab/issues/172

**Comment by samreid** [comment] 2024-08-20 15:39
We also discussed at standup, and since we have no reproducible way to create the problem and it seems very rare, we recommend closing the issue.

**Closed as completed by samreid** 2024-08-20 15:39 UTC
Labels: type:bug, type:wontfix
