### ISSUE TITLE
Why did the question mark disappear?

### ISSUE THREAD

**Issue by zepumph** [phetsims/density-buoyancy-common#243] opened 2024-06-28 21:42 UTC
Promoting TODO to issue

**Comment by samreid** [comment] 2024-07-03 19:22
The flip side of this question (which may help us get to the heart of the matter) is: If tandem is optional, why is there no type error when we did not specify a default for it in Mass.ts?

**Comment by samreid** [comment] 2024-08-03 21:40
I tried TypeScript 5.4.4 to see if anything was different, but it had the same behavior.

Here is a screenshot of that part:

<img width="1131" alt="image" src="https://github.com/user-attachments/assets/ba4e9a13-0dac-46c9-9b69-a143ff00a84a">

My new hypothesis is that WebStorm is doing its best to find the declaration of `tandem` to refer to, and it comes up with this location:

```ts
// Options for creating a PhetioObject
type SelfOptions = StrictOmit<Partial<PhetioElementMetadata>, 'phetioTypeName' | 'phetioArchetypePhetioID' |
  'phetioIsArchetype' | 'phetioEventType'> & {

  // This is the only place in the project where this is allowed
  tandem?: Tandem; // eslint-disable-line bad-sim-text
```

At this location, there is a question mark. Perhaps this is preferable to WebStorm trying to show intermediate computed types at each point.

Based on this, I feel the issue is OK to close (and remove the TODO). Let's check in with @zepumph

**Comment by samreid** [comment] 2024-08-04 01:58
On second thought, this issue seems good to close. I removed the TODO, and the extraneous `?`. We can discuss further as needed. Closing.

**Closed as completed by samreid** 2024-08-04 01:58 UTC
Labels: dev:code-review, status:ready-for-review
