### ISSUE TITLE
Shapes screen: Change the slider labels based on the shape type

### ISSUE THREAD

**Issue by arouinfar** [phetsims/density-buoyancy-common#348] opened 2024-08-16 21:07 UTC
Possibly related to #347 

I expected a block with the maximum height and minimum width to be equivalent to a block with the min height and max width.

On first glance, the blocks look similar in dimension, but the depths appear to be different. 
<img width="212" alt="image" src="https://github.com/user-attachments/assets/9cc3b666-319e-40d0-af43-86104910ebaa">
<img width="183" alt="image" src="https://github.com/user-attachments/assets/bd695ae2-879d-4cfc-9044-f2a457eacc7d">

This looks like a bug to me.

**Comment by samreid** [comment] 2024-08-16 22:39
I confirmed the ranges are both 0-1, so the problem is more likely #347. On hold until we figure that out.

**Comment by samreid** [comment] 2024-08-16 22:53
For cubes, height sets the height, but width sets the width and depth (where width=depth). It was really obvious at a different camera angle:

<img width="769" alt="image" src="https://github.com/user-attachments/assets/380485c4-66a4-469a-a722-b019daffc712">

How should we proceed?

**Comment by DianaTavares** [comment] 2024-08-16 23:25
I remember having this discussion in the past with JO when he develops this screen. We have 3D objects, but only controls to modify two dimensions. In those days, we decided that one of the control modify 2 variables (width modifies width and dept) because I never thought of doing a comparison as the one that Amy did. 
I think that we can make that each control modify .5 in the third dimension, in ca case, when we have equal values in the slider, we have cubes, for example for blocks, and circles bases for the cylinders. other option?

**Comment by samreid** [comment] 2024-08-17 04:10
> I think that we can make that each control modify .5 in the third dimension,

Does this mean that changing the "height" of a vertical cylinder also changes its radius? (Or the foci if it is an elliptical cylinder?)

What if we keep the functionality as it is and rename the controls to "Height" and "Width & Depth"?

**Comment by samreid** [comment] 2024-08-19 15:55
We would like to proceed by changing the labels. 

For cubes and duck, ellipsoid
* Height
* Width & Depth

For vertical cylinder, cone, inverted cone
* Height
* Radius

For horizontal cylinder
* Radius
* Width

@zepumph says autoselect on the dynamic texts would be nice and not too difficult to instrument. @arouinfar says if it becomes difficult, it is not necessary.

UPDATE: @zepumph says autoselect will probably not be easy here, actually.

**Comment by samreid** [comment] 2024-08-19 22:15
Fixed in the commits. I also renamed the tandems to be about `vertical` and `horizontal` to help keep things organized. If I left the tandems as they were, we would have the awkward case of the `widthSlider` being labeled "radius" or other mismatches. I also instrumented the DerivedStringProperty instances so they can be seen in autoselect, but I wasn't sure that was necessary. I also wrote a TODO to ask @zepumph if we should prefer a DynamicProperty for any reason. @zepumph can you please code review?

@arouinfar or @DianaTavares can you please check the runtime behavior?

**Comment by arouinfar** [comment] 2024-08-19 22:48
@samreid looks good on main. 

> I also renamed the tandems to be about `vertical` and `horizontal` to help keep things organized. 

Good idea! Let's also rename the underlying properties to match, `verticalRatioProperty` and `horizontalRatioProperty`.

>  I also instrumented the DerivedStringProperty instances so they can be seen in autoselect, but I wasn't sure that was necessary. 

Thanks @samreid. I don't think the DerivedStringProperties are totally necessary, but they are nice to have to support autoselect.

**Comment by samreid** [comment] 2024-08-20 02:43
I renamed the underlying properties.

**Comment by DianaTavares** [comment] 2024-08-20 15:37
It looks wonderful! thanks!!

**Comment by zepumph** [comment] 2024-08-20 21:03
>    // TODO: Would this be clearer or better using DynamicProperty? See https://github.com/phetsims/density-buoyancy-common/issues/348


No, I like it the way it is, because there isn't the extra logic of a Property value holding an object with a Property to listen to on it. (like massProperty=>mass.materialProperty).

**Comment by zepumph** [comment] 2024-08-20 21:10
All looks great. Thanks.

**Closed as completed** 2024-08-20 21:37 UTC
Labels: type:bug, status:ready-for-review
