### ISSUE TITLE
General layout and spacing changes

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#184] opened 2024-06-10 15:41 UTC

**Comment by zepumph** [comment] 2024-06-10 15:43
I wonder if the track size could help here:
https://github.com/phetsims/density-buoyancy-common/blob/362b124bb5b018a7b756e84dc734bc5a34b902cb/js/common/view/MaterialMassVolumeControlNode.ts#L417

But I wonder what text maxWidths we will need to change because of it.

**Comment by AgustinVallejo** [comment] 2024-06-10 17:07
Spoke with @DianaTavares regarding also the slider spacing in https://github.com/phetsims/density-buoyancy-common/issues/148 and we decided in favour of the following strategy, we'll go down the list until the space seems confortable, i.e. the last items are the most drastic changes:

- [x] Make all screen margins smaller, like the ones in Lab.
- [ ] Reduce width of the Density and Submerged readout panels, as they are the ones that overlap with the pool slider.
- [ ] Move the pool a bit to the left. To achieve this, two things would have to happen first:
    - [ ] Reduce max width of forces panel
    - [ ] Make the beaker smaller

Diana advised against reducing the mass and volume slider widths since some materials (Like Styrofoam shown below) already have a tiny operability window... Although I think that could be customized for those materials, as those MassVolumeSliders already have a lot of range customization options.

![image](https://github.com/phetsims/density-buoyancy-common/assets/37052186/eb54e44b-f55f-4591-aab5-e64f8c6bdc35)

**Comment by AgustinVallejo** [comment] 2024-06-10 18:10
Made all margins across the three sims smaller (nor using MARGIN_SMALL = 5). And the default layout is good for the pool slider. However, more changes are needed for the StringTest to work fully.

**Comment by AgustinVallejo** [comment] 2024-06-11 21:16
I believe this is done. The Compare screen is no longer overlapping but does have some odd behavior which we should take a look into. 

![image](https://github.com/phetsims/density-buoyancy-common/assets/37052186/565d40a8-363a-462e-a518-5c2a4f1d2ae8)

Besides that, could you review please, @DianaTavares

**Comment by DianaTavares** [comment] 2024-06-12 16:42
The panels don't overlap!! Thanks for the work!

**Comment by zepumph** [comment] 2024-06-12 17:28
Let's clean up some max widths though before closing, as @AgustinVallejo recommends.

![image](https://github.com/phetsims/density-buoyancy-common/assets/6856943/b20eb5af-6e02-4f1e-a933-33c7b80d1e62)

**Comment by DianaTavares** [comment] 2024-06-13 00:32
Ok! then I am assigning @AgustinVallejo to clean that, and  delete ready-for-review, until that change is done.

**Comment by AgustinVallejo** [comment] 2024-06-13 22:00
Now it's done, closing

**Comment by samreid** [comment] 2024-06-14 02:51
I saw that after the commit https://github.com/phetsims/density-buoyancy-common/commit/23ad1613cdb5f5392ae31fbd821d23dfc79421a7 which was merged in https://github.com/phetsims/density-buoyancy-common/commit/1f06e646f3e4a9397b3f93919ea729453351e584 caused ct to fail each column. 

I could reproduce an assertion error by launching buoyancy => compare screen => choose a radio button like "same volume"

<img width="1286" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/679486/54a629d5-0355-4214-8ccc-d7ca0b8d6d3a">

So I'll revert it for now and let's take a look.

**Comment by samreid** [comment] 2024-06-14 03:12
I explored in this area but there is an unexplained -Infinity width on the `numberControlPanel` that I could use help with.

**Comment by samreid** [comment] 2024-06-14 15:20
@zepumph @AgustinVallejo and I fixed this in the commit, closing.

**Closed as completed by samreid** 2024-06-14 15:20 UTC
Labels: dev:help-wanted
