### ISSUE TITLE
Add safety assertion

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#93] opened 2024-02-06 19:55 UTC
Based on a TODO and relieving https://github.com/phetsims/density-buoyancy-common/issues/86 of its duties, there seems to be a simple assertion to be added. More context needed tho.

The TODO now points to this issue.

**Comment by samreid** [comment] 2024-04-29 14:52
I looked at ways to solve this with type checking, but it was over my head. Here is a patch that adds the assertion.

<details>

```diff

Subject: [PATCH] imageable
---
Index: js/common/model/Mass.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/Mass.ts b/js/common/model/Mass.ts
--- a/js/common/model/Mass.ts	(revision 6f71d7d44ac14378fc867ced8ca174f1145b5f6e)
+++ b/js/common/model/Mass.ts	(date 1714402038355)
@@ -94,7 +94,9 @@
   }
 } );
 
-type MaterialNonCustomIdentifier = 'ALUMINUM' | 'BRICK' | 'COPPER' | 'ICE' | 'PLATINUM' | 'STEEL' | 'STYROFOAM' | 'WOOD';
+const MaterialNonCustomIdentifierValues = [ 'ALUMINUM', 'BRICK', 'COPPER', 'ICE', 'PLATINUM', 'STEEL', 'STYROFOAM', 'WOOD' ] as const;
+type MaterialNonCustomIdentifier = typeof MaterialNonCustomIdentifierValues[number];
+
 type MaterialIdentifier = MaterialNonCustomIdentifier | CustomMaterialName;
 
 const materialToEnum = ( material: Material ): MaterialEnumeration => MaterialEnumeration[ ( ( material.identifier as MaterialIdentifier | null ) || CUSTOM_MATERIAL_NAME ) ];
@@ -364,8 +366,10 @@
             } );
           }
           else {
-            // TODO: does this need an assertion just in case? https://github.com/phetsims/density-buoyancy-common/issues/93
-            this.materialProperty.value = Material[ materialEnum.name as MaterialNonCustomIdentifier ];
+            const nonCustomMaterialName = materialEnum.name as MaterialNonCustomIdentifier;
+            console.log( nonCustomMaterialName );
+            assert && assert( MaterialNonCustomIdentifierValues.includes( nonCustomMaterialName ), 'unknown material' );
+            this.materialProperty.value = Material[ nonCustomMaterialName ];
           }
           enumLock = false;
           densityLock = false;

```

</details>

However, I decided not to commit since I could never trigger that console.log to run, despite testing in several screens across density and buoyancy sims.

**Comment by zepumph** [comment] 2024-04-29 15:52
I added the assertion to accompany all the type casts, but the issue is that `EnumerationValue` doesn't have a list of values in type space, and the string-literal pattern does. If we wanted to convert `materialEnumProperty` to a string union property (pretty simple, but requires a migration rule), then that would probably be best. We could also close this if desired.

**Comment by samreid** [comment] 2024-05-02 11:53
The commit looks reasonable and it still seems like a good idea to reduce complexity on the migration side unless changes are required. So this seems good to close.

**Closed as completed by samreid** 2024-05-02 11:53 UTC
