### ISSUE TITLE
Blocks can be dragged into the geometry of the scale

### ISSUE THREAD

**Issue by samreid** [phetsims/density-buoyancy-common#32] opened 2021-08-10 19:54 UTC
From #5 and related to #22, I observed that a block can be dragged into the geometry of the scale:

![Kapture 2021-08-10 at 13 52 24](https://user-images.githubusercontent.com/679486/128926161-a01cabe3-6126-4fae-9e1e-71df1dda3517.gif)

**Comment by jonathanolson** [comment] 2021-08-10 20:37
Correct, the physics system allows a certain amount of slip. Not desirable but expected. @DianaTavares thoughts?

**Comment by samreid** [comment] 2021-08-10 22:33
Reducing the stiffness of the RevoluteConstraint when in contact with the scale may help?  But @jonathanolson said that is a somewhat complicated solution.

**Comment by DianaTavares** [comment] 2021-08-11 00:14
I think that the problem is also related to this issue: https://github.com/phetsims/density/issues/54, where the block can get stuck behind the scale and was marked as "wontfix". I think is the same for this issue.

**Comment by AgustinVallejo** [comment] 2024-02-09 18:52
The other issue was closed as not planned, will do the same here

**Closed as not planned by AgustinVallejo** 2024-02-09 18:52 UTC
Labels: type:bug, type:wontfix, dev:code-review
