### ISSUE TITLE
HSeparator between massVolumeControls are gone

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/density-buoyancy-common#198] opened 2024-06-13 15:11 UTC
![image](https://github.com/phetsims/density-buoyancy-common/assets/37052186/77425397-88d0-445b-bd31-4b62d9d11a6d)

**Comment by samreid** [comment] 2024-06-13 15:17
This was caused by a regression in https://github.com/phetsims/scenery/commit/eeafec1f606e46e0dc8d8a89e86fbef8501b74f8, heads up @zepumph

**Comment by AgustinVallejo** [comment] 2024-06-13 15:31
@samreid and I pushed changes above, paging MK for review.

**Comment by samreid** [comment] 2024-06-13 15:53
@zepumph and I reviewed the change and it seems good, closing.

**Closed as completed by samreid** 2024-06-13 15:53 UTC
Labels: status:ready-for-review
