### ISSUE TITLE
Grab sound shouldn't be heard until object is moved 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#190] opened 2024-06-12 17:36 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1095, I am hearing the grab/release sounds when tabbing through the traversal order when a moveable object has focus. I don't think I should hear those sounds until I move the object. 

**Steps to reproduce**
For example tab through the Compare Screen --you will hear the sounds when the blocks and scale have focus (at least that is what happens in other sims--FEL for example).

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy‬
URL: https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.9/phet/buoyancy_all_phet.html
Version: 1.0.0-dev.9 2024-06-12 15:13:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
Language: en-US
Window: 1380x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by samreid** [comment] 2024-06-12 23:04
I also observed that the only way to "drop" a tab-selected item is to tab away from it, and we are not using (and not planning to use) the grab drag interaction implementation. I asked about this and was told that the behavior is by design, that tabbing to an object to grab it and tabbing away to drop it is acceptable for this simulation. I don't recall whether @zepumph or @DianaTavares was the one I was talking to.  @zepumph or @DianaTavares can you chime in?

**Comment by DianaTavares** [comment] 2024-06-13 01:20
Let's discuss this in the design meeting because I don't consider myself an expert in sounds. My decisions are based on "what we did in MSS" and compared with what has been done in other simulations. The true, is that I thought that all the sounds were common code that is already established how it should sound. 

In this situation, I identify that:

1. On MSS,  I hear the grab/release sounds when the planet is moved. Then any time I click the arrows to move the planet, the grab/release is played, and not with the tab as currently Buoyancy.  Geometric Optics doesn't have a sound to  grab/release the object. I didn't find another simulation that present a similar situation as Buoyancy to compare.  

2. The "the grab drag interaction". I guess that is when the user needs to click the space to grab an object, like B&SE: 
![image](https://github.com/phetsims/density-buoyancy-common/assets/26031501/bd4610fa-4151-4dff-bef4-d41080360e5d)

Many simulations have it, but also many simulations don't. My idea (just by comparing, not because I really know the reason), of when this iteration is used is when moving the objects by dragging is important for the learning goal. For example, in B&SE is important to move the balloon to understand the movement of the charges (the most important concept of the sim). While in MSS and Optics, moving by dragging the object is one of the variables. The most important is to leave the object in one place, and then analyze how that position affects all the phenomena. MSS and Optics don't need to click space to drag an object, they use only the lab and arrows. 

Dragging in Buoyancy don't correspond with any of these situations. I didn't' find other simulation where the dragging has the same goal that in Buoyancy. Position is not a variable, continuously movement is not key for the learning goal. In Buoyancy we move to measure, move to put the object inside and outside the pool. Also, this simulation has gravity!!! (when you drop the object gravity affects the object and fall, I only think in ESP with this behavior, and it doesn't have sounds neither alternative inputs). In Buoyancy then probably is better to let the student know  "you are going to drag an object, that means that you are carrying it, adding a force to the system" and "you are going to drop the object and gravity/Buoynacy  are going to act". Then "the grab drag interaction" can be a good idea.

**Comment by Nancy-Salpepi** [comment] 2024-06-13 01:26
Hey @DianaTavares I agree that a discussion during design meeting would be good.

I wanted to give you the dev version for FEL that QA just tested for another sim to compare to: 
https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.32/phet/faradays-electromagnetic-lab_all_phet.html

**Comment by DianaTavares** [comment] 2024-06-13 21:35
In the design meeting today, we decided that this simulation needs to implement “the grab drag interaction”, that plays de grab/release sound, only when the user clicks space to grab/release.

**Comment by samreid** [comment] 2024-06-13 21:36
More notes from the design meeting:

Blocks and other draggable objects make the “grabbed” sound on focus because they are technically also “grabbed” and not subject to gravity. This deviates slightly from sims like FEL where draggable objects don’t make the “grabbed” sound until you use the arrow keys to move it.

NS: To release a block, you need to change your focus and tab away from it. This was unintuitive.
AR: This is also problematic for pan and zoom. Sim could pan away from the released block and you won’t see what happens to it.

GrabDragInteraction is a good fit here. Let’s use it!

Consensus: **Rewrite to use the grab drag interaction for blocks, so the user can release it without tabbing to change focus. Sounds will only play on grab/release (not on focus/blur)**

**Comment by zepumph** [comment] 2024-06-14 16:21
`GrabDragInteraction` work to be done in https://github.com/phetsims/density-buoyancy-common/issues/209. On hold until we can confirm.

**Comment by samreid** [comment] 2024-08-13 15:55
The sound now happens on grab/release, closing.

**Closed as completed by samreid** 2024-08-13 15:55 UTC
Labels: type:bug, dev:sound, dev:alt-input
