### ISSUE TITLE
block at min density will bounce indefinitely on Mercury

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#404] opened 2024-09-14 21:07 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
14.6.1

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1141 in Buoyancy Basics on the Explore Screen, a block with a density of .01 kg/L will continually bounce on Mercury. 

**Steps to reproduce**
1. In Basics, go to the Explore Screen and move the Density slider to the minimum value
2. Change the Fluid to Mercury

**Visuals**

https://github.com/user-attachments/assets/8b5c4195-833b-4143-b5f1-2c3cb4584ee1

**Comment by KatieWoe** [comment] 2024-09-23 20:07
Some of the other materials/densities have odd behavior too. Saltwater doesn't bounce at all and it looks a bit odd.
![morefunk](https://github.com/user-attachments/assets/5fa9896e-6f1b-46c7-bed2-a9d11ef2c033)

**Comment by DianaTavares** [comment] 2024-09-25 15:42
I also get these behaviors, same: low-density block and high-density fluid:
 
![buoyancy](https://github.com/user-attachments/assets/f4c581b2-2f61-4aca-afc1-3518b3b01942)

**Comment by zepumph** [comment] 2024-10-03 19:14
1. In buoyancy, when minCustomMass was .1, it  should be .5 instead
2. in Buoyancy basics, min custom density should be .1 instead of .01.


```diff
Subject: [PATCH] Node from the vbox needs to be set to invisible, https://github.com/phetsims/density-buoyancy-common/issues/415
---
Index: js/common/model/Material.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/Material.ts b/js/common/model/Material.ts
--- a/js/common/model/Material.ts	(revision 3bc283c608f96c20bada618bf0c1ceeb07646d9f)
+++ b/js/common/model/Material.ts	(date 1727982771091)
@@ -404,7 +404,7 @@
     nameProperty: DensityBuoyancyCommonStrings.material.materialTStringProperty,
     hidden: true,
     colorProperty: DensityBuoyancyCommonColors.materialTColorProperty,
-    density: 950 // Same as the Human's average density
+    density: Material.HUMAN.density
   } );
 
   public static readonly MATERIAL_U = new Material( packageJSON.name === 'buoyancy' ? SOLIDS_TANDEM.createTandem( 'materialU' ) : Tandem.OPT_OUT, {
Index: js/buoyancy/view/BuoyancyLabScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/buoyancy/view/BuoyancyLabScreenView.ts b/js/buoyancy/view/BuoyancyLabScreenView.ts
--- a/js/buoyancy/view/BuoyancyLabScreenView.ts	(revision 3bc283c608f96c20bada618bf0c1ceeb07646d9f)
+++ b/js/buoyancy/view/BuoyancyLabScreenView.ts	(date 1727982535089)
@@ -116,7 +116,7 @@
         visiblePropertyOptions: {
           phetioFeatured: true
         },
-        minCustomMass: 0.1,
+        minCustomMass: 0.5,
         maxVolumeLiters: maxBlockVolume
       }
     ) ] );
Index: js/buoyancy/view/BuoyancyExploreScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/buoyancy/view/BuoyancyExploreScreenView.ts b/js/buoyancy/view/BuoyancyExploreScreenView.ts
--- a/js/buoyancy/view/BuoyancyExploreScreenView.ts	(revision 3bc283c608f96c20bada618bf0c1ceeb07646d9f)
+++ b/js/buoyancy/view/BuoyancyExploreScreenView.ts	(date 1727982535098)
@@ -51,7 +51,7 @@
       model.blockB,
       this.popupLayer, {
         tandem: tandem,
-        minCustomMass: 0.1
+        minCustomMass: 0.5
       }
     );
 
Index: js/buoyancy-basics/view/BuoyancyBasicsExploreScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/buoyancy-basics/view/BuoyancyBasicsExploreScreenView.ts b/js/buoyancy-basics/view/BuoyancyBasicsExploreScreenView.ts
--- a/js/buoyancy-basics/view/BuoyancyBasicsExploreScreenView.ts	(revision 3bc283c608f96c20bada618bf0c1ceeb07646d9f)
+++ b/js/buoyancy-basics/view/BuoyancyBasicsExploreScreenView.ts	(date 1727982535080)
@@ -55,7 +55,7 @@
         ownsCustomDensityRange: false,
         customKeepsConstantDensity: true,
         tandem: tandem,
-        minCustomMass: 0.1,
+        minCustomMass: 0.5,
         maxCustomMass: 15
       }
     );

**Comment by zepumph** [comment] 2024-10-04 13:19
working on this now since I hope it is simple and easy.

**Comment by zepumph** [comment] 2024-10-04 13:44
Alright, we increased the min custom density in B:B:Explore, and increased the min custom mass in B:Lab and B:Explore. QA, please do some testing around the changes, for example in studio, to make sure we didn't cause any issues in certain cases where the mass or density is derived to be a (now) unsupported value).

**Comment by Nancy-Salpepi** [comment] 2024-10-07 17:10
I no longer get the endless bouncing in rc.2.
Closing.

**Comment by KatieWoe** [comment] 2024-10-07 17:14
I was able to get this again in https://github.com/phetsims/qa/issues/1149. If you fill the bottle in the last screen of the Density sim fully with air it has a density of .01 kg/L and will bounce infinitely on a max density fluid.
![bouncebottle](https://github.com/user-attachments/assets/174956e8-edfa-42d3-aa51-795e6ee19cca)

**Comment by Nancy-Salpepi** [comment] 2024-10-07 17:16
nice find Katie!

**Comment by zepumph** [comment] 2024-10-07 17:50
I could see us doing nothing about it and just closing the issue. I could also see us trying to work out some other solution. We already decided in other places that trying to adjust how the physics behaves was too challenging and nerve racking this late in the publication, and as a result we increased the min density so that this kind of thing wasn't possible. I believe double checking with @DianaTavares is best here. My thought would be to close this.

**Comment by kathy-phet** [comment] 2024-10-07 18:59
I agree with MK that this is a corner case, and we should close as won't fix.

**Comment by samreid** [comment] 2024-10-07 19:06
This is caused by error accumulation in the physics engine. We can address this problem by reducing the p2 timestep from the current value of `1 / 120` to about `1 / 540`. However, this is a very risky change that will impact behavior everywhere and have more significant performance implications. Therefore, we do not recommend changing the time step.

@zepumph and I found that we can change the bottle mass from 0.1kg to 0.3kg and that is enough to prevent the bouncing. This is much more well-isolated and less risky solution, if we want to do anything. Furthermore, when we faced similar bouncing problems, we solved it by adjusting the min/max densities to reduce the occurrence of bouncing. So adjusting the bottle mass would be in line with our prior decisions.

@DianaTavares do you see any problems with changing the bottle mass from 0.1kg (current value) to 0.3kg (proposed value that fixes the bouncing)?

**Comment by Nancy-Salpepi** [comment] 2024-10-07 21:01
Also in studio, if I customize the density material of the mystery block I can get it to bounce indefinitely. (eg. a density of 0.8 will cause the block to keep bouncing on mercury). I think designers will realize not to use this value, but wanted to note that this can happen.

**Comment by zepumph** [comment] 2024-10-08 16:35
@DianaTavares @samreid and I like increasing the mass of the empty bottle to .5kg. As for studio, we are not worried about that since all PhET-iO studio customizations involve a certain level of design and testing.

**Comment by KatieWoe** [comment] 2024-10-08 19:30
Looks good!

**Comment by zepumph** [comment] 2024-10-10 15:47
From slack:


>Kathy Perkins
:spiral_calendar_pad:  [Yesterday at 19:42](https://phetsims.slack.com/archives/C06EBMJPYNB/p1728524574756819)
Hey Buoyancy team,
Congratulations on the publication!! So much hard work and an amazing sim! The teachers will LOVE it!
I wanted to follow-up on one of the last changes that was made and just make sure the team realizes on the ramifications of it and agrees that its the preferred of the two options - and that is the increase of the plastic bottle weight from 0.1 to 0.5 kg.
https://github.com/phetsims/density-buoyancy-common/issues/404
We fiddled with that plastic bottle a lot in design, and we have it as a taking up "0 volume" on its own ... so now it is a 0.5kg and 0L object. You can fill the object with 10L of 3.15 kg/L concrete and see that the bottle displaces 10L of water. The "system" density used to be 3.16kg/L ... just a tad more, due to the mass we had assigned to our "thin plastic", but now the system density is affected a lot more by mass of the bottle - bumping it to 3.20kg/L. And its an even bigger difference when we fill with less dense material ... Gasoline goes from 0.68 to 0.73 kg/L instead of just to 0.69 kg/L. I want to make sure this was realized ... since for this screen it seems like a bigger deal pedagogically than other places where the minimum mass was increased to 0.5 kg.
What does the team think? (My inclination is that the bouncing corner case is OK here, and the 0.1kg bottle is better/preferred for this context so it impacts the System density less. We could revert to 0.1kg this before we publicize.)
Please don't let this question to detract from the major accomplishment! I'm very excited for us!
Kathy (edited) 



>3 replies


>Diana Lopez
:spiral_calendar_pad:  [21 minutes ago](https://phetsims.slack.com/archives/C06EBMJPYNB/p1728573935536119?thread_ts=1728524574.756819&cid=C06EBMJPYNB)
I didn't think about the changes that you mentioned Kathy. You are right, it is a huge change now in the system density. And now i also think is OK the strange unlimited jumping when the bottle is empty and the fluid is super dense... is possible to go back to 0.1 kg? Sorry for not to think before well about this.


>Sam Reid
  [14 minutes ago](https://phetsims.slack.com/archives/C06EBMJPYNB/p1728574399058779?thread_ts=1728524574.756819&cid=C06EBMJPYNB)
It is straightforward to change, just a few busywork steps, so would be good to confirm the value before changing it. We saw little or no bouncing at 0.3kg (in the long run), and took 0.5kg just to be safe, but could just go back to 0.1kg. What do you recommend?


>Diana Lopez
:spiral_calendar_pad:  [9 minutes ago](https://phetsims.slack.com/archives/C06EBMJPYNB/p1728574678665829?thread_ts=1728524574.756819&cid=C06EBMJPYNB)
I think that 0.1kg is better, no matter the edges where it bounce. 
[@kathy](https://phetsims.slack.com/team/U98Q0AX7B)
, what do you think?



So let's proceed with reverting the bottle mass change, and doing a Maintenance release.

**Comment by kathy-phet** [comment] 2024-10-10 17:34
I agree, the smaller the better - so 0.1kg sounds ok to me.

**Comment by zepumph** [comment] 2024-10-10 17:56
Fixing now

**Comment by zepumph** [comment] 2024-10-10 18:00
Ready for rc + local spot check + production deploy for MR.

**Comment by zepumph** [comment] 2024-10-10 20:06
Mass increase has been reverted, and can be seen in these RCs (creating them as we speak):

https://phet-dev.colorado.edu/html/buoyancy/1.2.1-rc.1/phet/buoyancy_all_phet.html
https://phet-dev.colorado.edu/html/buoyancy-basics/1.2.1-rc.1/phet/buoyancy-basics_all_phet.html
https://phet-dev.colorado.edu/html/density/1.2.1-rc.1/phet/density_all_phet.html

**Comment by kathy-phet** [comment] 2024-10-10 20:41
@zepumph - We did not advertise anything about PhET-iO, so hoping even if this changed the API, you can just proceed and overwrite it, without worrying about migration anything.

**Comment by zepumph** [comment] 2024-10-11 16:06
Production MR complete:

https://phet-origin.colorado.edu/sims/html/buoyancy/latest/buoyancy_all.html

Closing

**Closed as completed by zepumph** 2024-10-11 16:06 UTC
Labels: type:bug, priority:2-high
