### ISSUE TITLE
Selecting Material Y freezes the sim [Safari]

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#192] opened 2024-06-12 18:52 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1095, seen with Safari but not Chrome:
Choosing Material Y on the Explore Screen freezes the sim. If I reload the sim, nothing is clickable. I have to open a new tab or window. 
This doesn't happen with the other mystery materials. 
Nothing appeared in the console.

**Steps to reproduce**
1. Using Safari, go to the Explore Screen
2. Select Material Y from the combobox

**Visuals**

https://github.com/phetsims/density-buoyancy-common/assets/87318828/d8662735-0599-4092-8155-8e8ddf797ca2

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy‬
URL: https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.9/phet/buoyancy_all_phet.html
Version: 1.0.0-dev.9 2024-06-12 15:13:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
Language: en-US
Window: 1380x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by samreid** [comment] 2024-06-12 20:11
This patch identifies the area of the problem, I'll continue investigating:

<details>

```diff

Subject: [PATCH] Whitespace, see https://github.com/phetsims/density-buoyancy-common/issues/189
---
Index: js/buoyancy/view/BuoyancyExploreScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/buoyancy/view/BuoyancyExploreScreenView.ts b/js/buoyancy/view/BuoyancyExploreScreenView.ts
--- a/js/buoyancy/view/BuoyancyExploreScreenView.ts	(revision 35e9d20881fc236083bee6a6cc7682e3952a0032)
+++ b/js/buoyancy/view/BuoyancyExploreScreenView.ts	(date 1718222999087)
@@ -114,7 +114,7 @@
           mass.volumeProperty.value = 0.003;
         }
         else if ( material === Material.MATERIAL_Y ) {
-          mass.volumeProperty.value = 0.001;
+          mass.volumeProperty.value = 0.003;
         }
       } );
     } );

**Comment by samreid** [comment] 2024-06-12 22:50
@zepumph and I saw that the change to Property to make it queue-based caused the locks to fail. We experimented that changing to stack-based solved the problem, but we also saw that rounding to TOLERANCE was another way to short circuit the cycles because they seemed caused by rounding errors. I'll commit momentarily.

**Comment by samreid** [comment] 2024-06-12 22:56
Migration tests are working well, fuzz tests are working well, safari is no longer crashing under material Y. I sneaked in deleting some unused intersection code. Closing.

**Comment by samreid** [comment] 2024-06-12 23:00
@zepumph said the internal material property had locks, and recommended using the 'stack' strategy in those cases. Let's assign @zepumph to review the above and take that next step.

**Comment by zepumph** [comment] 2024-06-13 17:26
Yes thanks. This code here is buggy without ensuring that we eagerly call the listeners during the lock. 

https://github.com/phetsims/density-buoyancy-common/blob/b4d88d1dedeb6998b84d931878061526e640e849/js/buoyancy/view/applications/BuoyancyApplicationsScreenView.ts#L123-L133

**Closed as completed by zepumph** 2024-06-13 17:26 UTC
Labels: type:bug, status:ready-for-review
